source 'https://github.com/CocoaPods/Specs.git'
# SCCocoaPods (private SSH source) removed — Standard Cyborg is defunct and the used
# pods (SSZipArchive public; scsdk/PoissonRecon local) don't need it.
# source 'git@github.com:StandardCyborg/SCCocoaPods.git'

inhibit_all_warnings!

platform :osx, '11.0'

target 'StandardCyborgFusion' do
  pod 'SSZipArchive'
  pod 'scsdk', :path => 'scsdk/'
  pod 'PoissonRecon', :podspec => 'StandardCyborgFusion/PoissonRecon.podspec'
  platform :ios, '13.0'
end


# Sadly Cocoapods cant do both osx and ios in same target, so we have to make
# a separate one for OSX.
target 'StandardCyborgFusionOSX' do
  pod 'SSZipArchive'
  pod 'scsdk', :path => 'scsdk/'
  pod 'PoissonRecon', :podspec => 'StandardCyborgFusion/PoissonRecon.podspec'
  platform :osx, '11.0'
end

target 'StandardCyborgFusionTests' do
  platform :osx, '11.0'
  pod 'scsdk', :path => 'scsdk/'
end

target 'TrueDepthFusion' do
  platform :ios, '13.0'
end

target 'VisualTesterMac' do
  platform :osx, '11.0'
  pod 'scsdk', :path => 'scsdk/'
end

target 'VisualTesteriOS' do
  platform :ios, '13.0'
  pod 'scsdk', :path => 'scsdk/'
end

target 'StandardCyborgAlgorithmsTestbed' do
  platform :ios, '13.0'
  pod 'scsdk', :path => 'scsdk/'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do | configuration |
      # Modern Clang (19+) flags so the 2018 C++ deps (esp. PoissonRecon) compile.
      _scWarn = '-Wno-shorten-64-to-32 -Wno-comma -Wno-deprecated-declarations ' \
                '-Wno-missing-template-arg-list-after-template-kw'
      configuration.build_settings['OTHER_CFLAGS'] = _scWarn
      configuration.build_settings['OTHER_CPPFLAGS'] = _scWarn

      # Suppress warnings about upgrading project to automatically select architectures
      configuration.build_settings.delete 'ARCHS'

      # Update minimum deployment target
      if configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 13.0
        configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
      if configuration.build_settings['MACOSX_DEPLOYMENT_TARGET'].to_f < 11.0
        configuration.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end

  # Re-apply modern-Clang source fixes to PoissonRecon (these live in Pods/, which is
  # regenerated by `pod install`, so patch here for a reproducible build).
  poisson = 'Pods/PoissonRecon'
  if File.exist?("#{poisson}/ZLIB/zconf.h")
    system(%(sed -i '' 's|#if !defined(MACOS) \&\& !defined(TARGET_OS_MAC)|#if !defined(__MACTYPES__)|' "#{poisson}/ZLIB/zconf.h"))
    system(%(sed -i '' 's|i<A.rows ;|i<A.rows() ;|g' "#{poisson}/Src/SparseMatrix.inl"))
    system(%(sed -i '' 's|(int)this->_data.size()|(int)_sz|g' "#{poisson}/Src/FEMTree.h"))
    puts '[post_install] Patched PoissonRecon for modern Clang'
  end
end

